# ========================================
# Production Environment Configuration
# ========================================

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never

# Security Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.devtoolkit: ERROR
    org.springframework.web: ERROR
    org.springframework.security: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # Railway captures console logs, no need for file logging in production
  # file:
  #   name: logs/devtoolkit-backend-prod.log
  # pattern:
  #   file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://www.thetoolarc.com,https://devtoolkit-ui-production.up.railway.app}

# File Upload Configuration
spring:
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  jmx:
    enabled: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
      influx:
        enabled: true 