# ========================================
# Staging Environment Configuration
# ========================================

# Server Configuration
server:
  port: 8080
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
  error:
    include-stacktrace: never
    include-message: never

# Security Configuration
jwt:
  secret: ${JWT_SECRET:stage-secret-key-must-be-changed-in-production}
  expiration: 86400000

# Logging Configuration
logging:
  level:
    com.devtoolkit: WARN
    org.springframework.web: ERROR
    org.springframework.security: ERROR
  file:
    name: logs/devtoolkit-backend-stage.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:https://stage-devtoolkit-ui.example.com}

# File Upload Configuration
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
      influx:
        enabled: true 